- name: create /opt/zgw folder
  file:
    path: /opt/zgw
    state: directory

- name: Create /opt/zgw/nginx-default.conf
  template:
    src: templates/nginx-default.conf.j2
    dest: /opt/zgw/nginx-default.conf
    owner: root
    mode: 0600
  notify: restart zgw

- name: Create /opt/zgw/postgis-initdb.sql
  template:
    src: templates/postgis-initdb.sql.j2
    dest: /opt/zgw/postgis-initdb.sql
    owner: root
    mode: 0644
  notify: restart zgw

- name: Create /opt/zgw/docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/zgw/docker-compose.yml
    owner: root
    mode: 0600
  notify: restart zgw

- name: Create /opt/zgw/.env
  template:
    src: templates/dot-env.j2
    dest: /opt/zgw/.env
    owner: root
    mode: 0600
  notify: restart zgw

- name: Create /opt/zgw/configure.sh
  template:
    src: templates/configure.sh.j2
    dest: /opt/zgw/configure.sh
    owner: root
    mode: 0600

- name: Create /etc/systemd/system/zgw.service
  template:
    src: templates/zgw.service.j2
    dest: /etc/systemd/system/zgw.service
    owner: root
    mode: 0644
  notify: restart zgw

- name: enable zgw service
  systemd:
    name: zgw
    enabled: yes
