- name: create /opt/zgw folder
  file:
    path: /opt/zgw
    state: directory

- name: Create /etc/nginx/sites-available/zgw
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/zgw
    owner: root
    mode: 0644
  when: not zgw_lock_nginx_configuration
  notify: restart nginx

- name: Create symlink /etc/nginx/sites-enabled/zgw
  file:
    src: /etc/nginx/sites-available/zgw
    dest: /etc/nginx/sites-enabled/zgw
    state: link
  notify: restart nginx

- name: Create /etc/nginx/snippets/security.conf
  template:
    src: templates/security.conf.j2
    dest: /etc/nginx/snippets/security.conf
    owner: root
    mode: 0644
  notify: restart nginx

- name: Create /etc/nginx/modules-available/10-disable-server-tokens.conf
  template:
    src: templates/10-disable-server-tokens.conf.j2
    dest: /etc/nginx/modules-available/10-disable-server-tokens.conf
    owner: root
    mode: 0644
  notify: restart nginx

- name: Create symlink /etc/nginx/modules-enabled/10-disable-server-tokens.conf
  file:
    src: /etc/nginx/modules-available/10-disable-server-tokens.conf
    dest: /etc/nginx/modules-enabled/10-disable-server-tokens.conf
    state: link
  notify: restart nginx

- name: Create /opt/zgw/postgis-initdb.sql
  template:
    src: templates/postgis-initdb.sql.j2
    dest: /opt/zgw/postgis-initdb.sql
    owner: root
    mode: 0644
  notify: restart zgw

- name: Create /opt/zgw/docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/zgw/docker-compose.yml
    owner: root
    mode: 0600
  notify: restart zgw

- name: Create /opt/zgw/.env
  template:
    src: templates/dot-env.j2
    dest: /opt/zgw/.env
    owner: root
    mode: 0600
  notify: restart zgw

- name: Create /opt/zgw/configure.sh
  template:
    src: templates/configure.sh.j2
    dest: /opt/zgw/configure.sh
    owner: root
    mode: 0700

- name: Create /etc/systemd/system/zgw.service
  template:
    src: templates/zgw.service.j2
    dest: /etc/systemd/system/zgw.service
    owner: root
    mode: 0644
  notify: restart zgw

- name: enable zgw service
  systemd:
    name: zgw
    enabled: yes
