- name: create /opt/alfresco folder
  file:
    path: /opt/alfresco
    state: directory

- name: Create /opt/alfresco/docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/alfresco/docker-compose.yml
    owner: root
    mode: 0600
  notify: restart alfresco

- name: Create /etc/systemd/system/alfresco.service
  template:
    src: templates/alfresco.service.j2
    dest: /etc/systemd/system/alfresco.service
    owner: root
    mode: 0644
  notify: restart alfresco

- name: enable alfresco service
  systemd:
    name: alfresco
    enabled: yes
